
################################################################################
# SPLASH BUNDLE DEV ROUTES
################################################################################

splash_debug_soap:
    path:     /soap-debug
    defaults:
        _controller: SplashBundle:DEV:debug
        
splash_debug_soap_filtered:
    path:     /soap-debug/{Type}
    defaults:
        _controller: SplashBundle:DEV:debug
        
splash_debug_soap_view:
    path:     /soap-debug/{Type}/{ObjectId}
    defaults:
        _controller: SplashBundle:DEV:debug
        
#splash_nodes_faker_dev_route:
#    path:     /dev
#    defaults:
#        _controller: NodesFakerBundle:DEV:index
