################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/pages.yaml'

################################################################
# Set any variables we need
variables:
    COMPOSER_MEMORY_LIMIT:        -1
    SYMFONY_DEPRECATIONS_HELPER:  disabled

################################################################
# Defined Pipeline Stages
stages:
  - Symfony-5
  - Symfony-6
  - Symfony-7
  - Builds

################################################################
# Functional Tests
################################################################

.functional:    &functional
    tags:
        - Dedicated
    artifacts:
        when: always
        reports:
            junit: "*-report.xml"

    ################################################################################
    # Install & Configure Environment
    before_script:
        ################################################################################
        # Install Symfony
        - composer update
    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - wall-e grumphp:quality
        - wall-e grumphp:stan
        # Execute PhpUnit Tests
        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml

    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Tests on SF 7
################################################################
sf7:php-8.3:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    stage:          Symfony-7
    allow_failure:  true
    variables:
        SYMFONY_REQUIRE:   7.*

sf7:php-8.2:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    stage:          Symfony-7
    allow_failure:  true
    variables:
        SYMFONY_REQUIRE:   7.*

################################################################
# Tests on SF 6
################################################################
sf6:php-8.3:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    stage:          Symfony-6
    variables:
        SYMFONY_REQUIRE:   6.4.*

sf6:php-8.2:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    stage:          Symfony-6
    variables:
        SYMFONY_REQUIRE:   6.4.*

sf6:php-8.1:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    stage:          Symfony-6
    variables:
        SYMFONY_REQUIRE:   6.4.*

################################################################
# Tests on SF 5
################################################################
sf5:php-8.2:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    stage:          Symfony-5
    variables:
        SYMFONY_REQUIRE:   5.4.*

sf5:php-8.1:
    <<: *functional
    image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    stage:          Symfony-5
    variables:
        SYMFONY_REQUIRE:   5.4.*
