################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:               symfony
  MYSQL_ROOT_PASSWORD:          Php-Bundle
  COMPOSER_MEMORY_LIMIT:        -1
  SYMFONY_DEPRECATIONS_HELPER:  disabled

################################################################
# Defined Pipeline Stages
stages:
  - symfony-4
  - symfony-5
#   - symfony-6
  - deploy

################################################################
# Functional Tests
################################################################

.core-tests:    &core-tests
    tags:
        - Dedicated
    services:
        - mysql:5.7
    artifacts:
        when: always
        reports:
            junit: "*-report.xml"

    ################################################################################
    # Install & Configure Environnement
    before_script:
        # Setup Travis
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/configure.sh  | sh
        # Deploy Symfony Files
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
        # Setup Symfony Version & Create Database
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
        # Install Symfony
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh

    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
      # Execute PhpUnit Tests
        - vendor/bin/phpunit

    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Tests on SF 6
################################################################
# sf6:php-8.1:
#     image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
#     <<: *core-tests
#     stage:      symfony-6
#     variables:
#         SF_VERSION:   "^6.1"
#
# sf6:php-8.0:
#     image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
#     <<: *core-tests
#     stage:      symfony-6
#     variables:
#         SF_VERSION:   "^6.1"

################################################################
# Tests on SF 5
################################################################
sf5:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *core-tests
    stage:      symfony-5
#     variables:
#         SF_VERSION:   "^5.4"

sf5:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *core-tests
    stage:      symfony-5
#     variables:
#         SF_VERSION:   "^5.4"

sf5:php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    <<: *core-tests
    stage:      symfony-5
#     variables:
#         SF_VERSION:   "^5.4"

################################################################
# Tests on SF 4
################################################################
sf4:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *core-tests
    stage:      symfony-4
    variables:
        SF_VERSION:   "~4.4"

sf4:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *core-tests
    stage:      symfony-4
    variables:
        SF_VERSION:   "~4.4"

sf4:php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    <<: *core-tests
    stage:      symfony-4
    variables:
        SF_VERSION:   "~4.4"

#################################################################
## Build Documentation
#################################################################
pages:
    image:    registry.gitlab.com/splashsync/php-console:pages
    stage:    deploy
    tags:
      - Dedicated
    services:
      - docker:dind
    ################################################################################
    # Run Test Script
    script:
      # Run Composer to Build deps
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
      # Build Documentation
      - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public
