################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/pages.yaml'

################################################################
# Set any variables we need
variables:
    COMPOSER_MEMORY_LIMIT:        -1
    SYMFONY_DEPRECATIONS_HELPER:  disabled

################################################################
# Defined Pipeline Stages
stages:
  - Symfony-4
  - Symfony-5
  - Symfony-6
  - Builds

################################################################
# Functional Tests
################################################################

.functional:    &functional
    tags:
        - Dedicated
    artifacts:
        when: always
        reports:
            junit: "*-report.xml"

    ################################################################################
    # Install & Configure Environment
    before_script:
        ################################################################################
        # Install Symfony
        - composer require symfony/http-kernel:$SF_VERSION
        - composer update
    ################################################################################
    # Run Test Script
    script:
        # Execute Grumphp Testsuite
        - wall-e grumphp:quality
        - wall-e grumphp:stan
        # Execute PhpUnit Tests
        - vendor/bin/phpunit --log-junit $CI_PROJECT_DIR/full-report.xml

    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# Tests on SF 6
################################################################
sf6:php-8.2:
     image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
     <<: *functional
     stage:      Symfony-6
     allow_failure: true
     variables:
         SF_VERSION:   "^6.4"

sf6:php-8.1:
     image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
     <<: *functional
     stage:      Symfony-6
     allow_failure: true
     variables:
         SF_VERSION:   "^6.4"

################################################################
# Tests on SF 5
################################################################
sf5:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *functional
    stage:      Symfony-5
    variables:
        SF_VERSION:   "^5.4"

sf5:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *functional
    stage:      Symfony-5
    variables:
        SF_VERSION:   "^5.4"

sf5:php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    <<: *functional
    stage:      Symfony-5
    variables:
        SF_VERSION:   "^5.4"

################################################################
# Tests on SF 4
################################################################
sf4:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *functional
    stage:      Symfony-4
    allow_failure: true
    variables:
        SF_VERSION:   "^4.4"

sf4:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *functional
    stage:      Symfony-4
    allow_failure: true
    variables:
        SF_VERSION:   "^4.4"
