        
################################################################################
# Define Test Matrix
matrix:
    include:          
        
        # Symfony 3.4 Branch       
        - php: 7.1
          env: SF_VERSION="3.4.*"     
          
        # Symfony 4.0 Branch
        - php: 7.1
          env: SF_VERSION="4.0.*"
        - php: 7.2
          env: SF_VERSION="4.0.*"       
        
        # Symfony 4.2 Branch
        - php: 7.1
          env: SF_VERSION="4.2.*"
        - php: 7.3
          env: SF_VERSION="4.2.*" 
          
        # Symfony 4.3 Branch
        - php: 7.1
          env: SF_VERSION="4.3.*"
        - php: 7.3
          env: SF_VERSION="4.3.*" 
          
    allow_failures:    
        - env: SF_VERSION="4.3.*"       
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

################################################################################
# Prepare Test Environement
before_install:    
    - echo "Configuring The Bundles"
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - ln -s public web
    
################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    # Setup Travis
    - bash src/Resources/travis/configure.sh
    # Setup Symfony Version if Required
    - bash src/Resources/travis/build_symfony.sh
    # Configure For Phpstan vs PHP Versions
    - bash src/Resources/travis/build_grumphp.sh
    # Install Symfony
    - bash src/Resources/travis/install.sh

################################################################################
# Run script
script:
    # Execute Grump Travis Testsuite 
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP > 7.0 => Execute CsFixer
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=csfixer; fi    
    # With PHP > 7.0 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=phpstan; fi   
    # Execute PhpUnit Tests 
    - vendor/bin/phpunit
    # Show Outdated Packages   
    - composer outdated    

################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always