        
################################################################################
# Define Test Matrix
matrix:
    include:          
        # Symfony 4.4 Branch
        - php: 7.2
          env: SF_VERSION="4.4.*"
        - php: 7.3
          env: SF_VERSION="4.4.*"
        - php: 7.4
          env: SF_VERSION="4.4.*"

    allow_failures:    
        - env: SF_VERSION="4.3.*"       
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

################################################################################
# TEST SCRIPTS
################################################################################

################################################################################
# Install & Configure Environnement
install:
  # Setup Travis
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh  | sh
  # Deploy Symfony Files
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
  # Setup Symfony Version & Create Database
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
  # Install Symfony
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh

################################################################################
# Run script
script:
    # Execute Grumphp Testsuite
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/grumphp.sh  | sh
#    - php vendor/bin/grumphp run -n --testsuite=travis
#    # With PHP > 7.0 => Execute CsFixer
#    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run -n --testsuite=csfixer; fi
#    # With PHP > 7.0 => Execute Phpstan
#    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run -n --testsuite=phpstan; fi
    # Execute PhpUnit Tests 
    - vendor/bin/phpunit

################################################################################
# Run After Script
after_script:
  - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/after.sh | sh

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Project language
language:   php
os:         linux
dist:       trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always