
#############################################        
# Import Config. from Generic Bundle
imports:
    - { resource: "./src/Resources/travis/travis.base.yml" }

################################################################################
# Project language
language: php
    
#################################################################################
## Project language
#language: php
## Allows use container-based infrastructure
#sudo: false
##sudo: required
#dist: trusty
#
#################################################################################
## Start mysql service
#services:
#  - mysql
#
#################################################################################
## Cache composer packages so "composer install" is faster
#cache:
#    directories:
#        - $HOME/.composer/cache/files
#
#################################################################################
## Define an environment variable
#env:
#    global:
#        - SYMFONY_DEPRECATIONS_HELPER=disabled
        
################################################################################
# Define Test Matrix
matrix:
    include:          
#        # Symfony 3.3 Branch       
#        - php: 7.0
#          env: SF_VERSION="3.3.*"        
#        - php: 7.1
#          env: SF_VERSION="3.3.*"        
          
        # Symfony 3.4 Branch       
        - php: 7.1
          env: SF_VERSION="3.4.*"
        - php: 7.2
          env: SF_VERSION="3.4.*"       
#          
#        # Symfony 4.0 Branch       
#        - php: 7.1
#          env: SF_VERSION="4.0.*"  STABILITY="dev"   
#        - php: 7.2
#          env: SF_VERSION="4.0.*"  STABILITY="dev"        
        
    allow_failures:
        - env: SF_VERSION="4.0.*"  STABILITY="dev"       
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

################################################################################
# Prepare Test Environement
before_install:
    
    - echo "Configuring The Bundles"
    - cp app/config/parameters.yml.dist app/config/parameters.yml
   
#    # Setup Travis
#    - bash src/Resources/travis/configure.sh
#    # Setup Symfony Version if Required
#    - bash src/Resources/travis/build_symfony.sh
#    # Configure For Phpstan vs PHP Versions
#    - bash src/Resources/travis/build_grumphp.sh
#      
#################################################################################
## Install composer dependencies,
## Create database, schema and fixtures
#install:   
#    
#
#
#    # Install Symfony
#    - bash src/Resources/travis/install.sh
#
#################################################################################
## Run script
#script:
#    # Execute Full Testsuite 
#    - bash src/Resources/travis/test_all.sh
#
#    
## After a build, send email notification with the build results
#notifications:
#  email:         
#    on_success: never # default: change
#    on_failure: never # default: always