
################################################################################
# NODES SOAP & NUSOAP WEBSERVICE ROUTES
################################################################################

# Main SOAP Acces
splash_main_soap:
    path:     /splash
    defaults:
        _controller: SplashBundle:Soap:main

# Connect & Test
splash_test_soap:
    path:     /splash-test
    defaults:
        _controller: SplashBundle:Soap:test

################################################################################
# CONNECTORS ACTION ROUTES
################################################################################

# Execute Connector Master Actions 
splash_connector_action_master:
    path:     /{connectorName}
    defaults:
        _controller: SplashBundle:Actions:master

# Execute Connectors Public Actions 
splash_connector_action:
    path:     /{connectorName}/{webserviceId}/{action}
    defaults:
        action:         index
        _controller:    SplashBundle:Actions:public

# Execute Connectors Secured Actions 
splash_connector_secured_action:
    path:     /{connectorName}/{webserviceId}/secured/{action}
    defaults:
        _controller: SplashBundle:Actions:secured