
################################################################################
# NODES SOAP & NUSOAP WEBSERVICE ROUTES
################################################################################

# Main SOAP Access
splash_main_soap:
    path:     /splash
    defaults:
        _controller: Splash\Bundle\Controller\SoapController::mainAction

# Connect & Test
splash_test_soap:
    path:     /splash-test
    defaults:
        _controller: Splash\Bundle\Controller\SoapController::testAction

################################################################################
# CONNECTORS ACTION ROUTES
################################################################################

# Execute Connector Master Actions 
splash_connector_action_master:
    path:     /{connectorName}
    defaults:
        _controller: Splash\Bundle\Controller\ActionsController::masterAction

# Execute Connectors Public Actions 
splash_connector_action:
    path:     /{connectorName}/{webserviceId}/{action}
    defaults:
        action:         index
        _controller:    Splash\Bundle\Controller\ActionsController::publicAction

# Execute Connectors Secured Actions 
splash_connector_secured_action:
    path:     /{connectorName}/{webserviceId}/secured/{action}
    defaults:
        _controller:    Splash\Bundle\Controller\ActionsController::securedAction