
################################################################################
# NODES SOAP & NUSOAP WEBSERVICE ROUTES
################################################################################

# Main SOAP Acces
splash_main_soap:
    path:     /soap
    defaults:
        _controller: SplashBundle:Soap:main

# Connect & Test
splash_test_soap:
    path:     /soap-test
    defaults:
        _controller: SplashBundle:Soap:test

################################################################################
# CONNECTORS ACTION ROUTES
################################################################################

# Execute Connectors Actions 
splash_connector_action:
    path:     /{ConnectorName}/{WebserviceId}/{Action}
    defaults:
        Action: index
        _controller: SplashBundle:Actions:index

