services:

    ########################################################################
    #   CONNECTORS MANAGER
    ########################################################################
    splash.connectors.manager:
        class: Splash\Bundle\Services\ConnectorsManager
        lazy:   false
        public: true
        arguments:
            -   "@=service('service_container').getParameter('splash')"
            -   !tagged "splash.connector"
            -   "@session"
        tags:
            - { name: kernel.event_listener, event: splash.connectors.commit,    method: onCommitEvent }   

    ################################################################################
    # Standalone Connector
    ################################################################################
    splash.connectors.standalone:
        class:      Splash\Bundle\Connectors\Standalone
        tags:       [ "splash.connector" ]
        arguments:  [ "@event_dispatcher" ]
        public:     true
        calls:
            - [ setContainer, [ "@service_container" ]]

    splash.connectors.standalone.form:
        class:      Splash\Bundle\Form\StandaloneFormType
        arguments:  [ "@event_dispatcher" ]
        public:     true
        tags:
            - { name: form.type }

            
########################################################################
#   CONNECTORS COMMANDS
########################################################################

#    splash.bundle.command.nodes.list:
#        class: Splash\Tasking\Command\CheckCommand
#        tags:    [ console.command ]
        
        