services:

    ########################################################################
    #   CONNECTORS MANAGER
    ########################################################################
    splash.connectors.manager:
        class: Splash\Bundle\Services\ConnectorsManager
        lazy:   false
        public: true
        arguments:
            -   "@=service('service_container').getParameter('splash')"
            -   !tagged "splash.connector"
            -   "@session"
        tags:
            - { name: kernel.event_listener, event: splash.connectors.commit,    method: onCommitEvent }   
            - { name: kernel.event_listener, event: splash.connectors.identify,  method: onIdentifyEvent, priority: 100}   
            - { name: kernel.event_listener, event: splash.connectors.update,    method: onUpdateEvent, priority: 100}   

    ################################################################################
    # Standalone Connector
    ################################################################################
    splash.connectors.standalone:
        class:      Splash\Bundle\Connectors\Standalone
        tags:       [ "splash.connector" ]
        arguments: 
            -   "@event_dispatcher"  
            -   "@logger"
        public:     true
        calls:
            - [ setContainer, [ "@service_container" ]]

    splash.connectors.standalone.form:
        class:      Splash\Bundle\Form\StandaloneFormType
        arguments:  [ "@event_dispatcher" ]
        public:     true
        tags:
            - { name: form.type }

    splash.connectors.standalone.widget.selftest:
        class:      Splash\Bundle\Templates\Widgets\SelfTestTemplate
        public:     true
        tags:
            - { name: "splash.standalone.widget", type : "selftest" }
        