services:

    ########################################################################
    #   CONNECTORS MANAGER
    ########################################################################
    connectors.manager:
        class: Splash\Bundle\Services\ConnectorsManager
        lazy:   false
        public: true
        arguments:
            -   "%splash%"
            -   "@event_dispatcher"
#            -   "@=service('doctrine.orm.entity_manager').getRepository('NodesCoreBundle:Node')"
#            -   "@logger" 
#        calls:
#            - [ setTranslator, [ "@translator" ]] 
#        tags:
#            - "splash.connector"
#            - { name: kernel.event_listener, event: splash.connectors.list,    method: onConnectorsListing }            


    ################################################################################
    # Sonata Admin Model Manager
    ################################################################################
    
    sonata.admin.manager.splash.objects:
        class:  Splash\Bundle\Admin\ObjectsModelManager
        autowire: true
    
    ################################################################################
    # Standalone Connector
    ################################################################################
    splash.connectors.standalone:
        class: Splash\Bundle\Connectors\Standalone
        tags: [ "splash.connector" ]
#        lazy:   false
#        public: true
#        arguments:
#            -   "@event_dispatcher"
##            -   "@=service('doctrine.orm.entity_manager').getRepository('NodesCoreBundle:Node')"
##            -   "@logger" 
##        calls:
##            - [ setTranslator, [ "@translator" ]] 
#        tags:
#            - { name: kernel.event_listener, event: splash.connectors.list,    method: onConnectorsListing }            
        
#    ########################################################################
#    # Splash Object Event Listener
#    # This Listner is Triggered on Any Object changes dont on ORM
#    # It will detect impacted Splash Objects and Dispatch Commits to Splash Server
#    Splash.Objects.EventListener:
#        class:      Splash\Bundle\EventListener\ObjectEventListener
#        tags:
#            - { name: doctrine.event_listener, event: postPersist,  method: postPersist }
#            - { name: doctrine.event_listener, event: postUpdate,   method: postUpdate }
#            - { name: doctrine.event_listener, event: preRemove,    method: preRemove }
#            
#    ########################################################################
#    # Splash Object Data Transformer
#    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
#    Splash.Objects.Transformer:
#        class:      Splash\Local\Objects\Transformer


########################################################################
#   CONNECTORS COMMANDS
########################################################################

#    splash.bundle.command.nodes.list:
#        class: Splash\Tasking\Command\CheckCommand
#        tags:    [ console.command ]
        
        