services:

    _defaults:
        autowire:           true
        autoconfigure:      true

    ########################################################################
    #   AutoWire for Controllers
    Splash\Bundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ########################################################################
    #   CONNECTORS MANAGER
    ########################################################################
    splash.connectors.manager:
        class: Splash\Bundle\Services\ConnectorsManager
        lazy:   false
        public: true
        arguments:
            -   "%splash%"
            -   !tagged "splash.connector"
        tags:
            - { name: kernel.event_listener, event: Splash\Bundle\Events\ObjectsCommitEvent,        method: onCommitEvent,  priority: 100 }
            - { name: kernel.event_listener, event: Splash\Bundle\Events\ObjectFileEvent,           method: onGetFileEvent, priority: 100 }
            - { name: kernel.event_listener, event: Splash\Bundle\Events\IdentifyServerEvent,       method: onIdentifyEvent,priority: 100}
            - { name: kernel.event_listener, event: Splash\Bundle\Events\IdentifyHostEvent,         method: onIdentifyByHostEvent, priority: 100}
            - { name: kernel.event_listener, event: Splash\Bundle\Events\UpdateConfigurationEvent,  method: onUpdateEvent,  priority: 100}

    # Autowiring
    Splash\Bundle\Services\ConnectorsManager:
        alias: splash.connectors.manager
        public: true

    ################################################################################
    # Standalone Connector
    ################################################################################
    splash.connectors.standalone:
        class:      Splash\Bundle\Connectors\Standalone
        public:     true

    splash.connectors.standalone.form:
        class:      Splash\Bundle\Form\StandaloneFormType
        arguments:  [ "@event_dispatcher" ]
        public:     true
        tags:
            - { name: form.type }

    splash.connectors.standalone.widget.selftest:
        class:      Splash\Bundle\Templates\Widgets\SelfTestTemplate
        public:     true
        tags:
            - { name: "splash.standalone.widget", type : "selftest" }

    ################################################################################
    # Connector Routes Builder
    ################################################################################
    Splash\Bundle\Services\ConnectorRoutesBuilder: ~

    ################################################################################
    # OAuth2 Connector Authentication
    ################################################################################
    # Splash\Bundle\Security\ConnectorAuthenticator: ~