services:

    _defaults:
        autowire: true
        autoconfigure: true

    ########################################################################
    #   AutoWire for Controllers
    Splash\Bundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ########################################################################
    #   CONNECTORS MANAGER
    ########################################################################
    splash.connectors.manager:
        class: Splash\Bundle\Services\ConnectorsManager
        lazy:   false
        public: true
        arguments:
            -   "@=service('service_container').getParameter('splash')"
            -   !tagged "splash.connector"
            -   "@session"
            -   "@?security.authorization_checker"
        tags:
            - { name: kernel.event_listener, event: Splash\Bundle\Events\ObjectsCommitEvent,        method: onCommitEvent,  priority: 100 }
            - { name: kernel.event_listener, event: Splash\Bundle\Events\ObjectFileEvent,           method: onGetFileEvent, priority: 100 }
            - { name: kernel.event_listener, event: Splash\Bundle\Events\IdentifyServerEvent,       method: onIdentifyEvent,priority: 100}
            - { name: kernel.event_listener, event: Splash\Bundle\Events\UpdateConfigurationEvent,  method: onUpdateEvent,  priority: 100}

    # Autowiring
    Splash\Bundle\Services\ConnectorsManager:
        alias: splash.connectors.manager
        public: true

    ################################################################################
    # Standalone Connector
    ################################################################################
    splash.connectors.standalone:
        class:      Splash\Bundle\Connectors\Standalone
        tags:       [ "splash.connector" ]
        arguments: 
            -   "@event_dispatcher"
            -   "@logger"
        public:     true
        calls:
            - [ setContainer, [ "@service_container" ]]

    splash.connectors.standalone.form:
        class:      Splash\Bundle\Form\StandaloneFormType
        arguments:  [ "@event_dispatcher" ]
        public:     true
        tags:
            - { name: form.type }

    splash.connectors.standalone.widget.selftest:
        class:      Splash\Bundle\Templates\Widgets\SelfTestTemplate
        public:     true
        tags:
            - { name: "splash.standalone.widget", type : "selftest" }
        