imports:
    - { resource: config/parameters.yml }
    - { resource: packages/framework.yml }
    - { resource: packages/doctrine.yml }
    - { resource: packages/splash.yml }
    
    
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true
    
# Debug Toolbar    
web_profiler:
    toolbar:             true    