imports:
    - { resource: config/parameters.yml }
    - { resource: packages/framework.yml }
    - { resource: packages/doctrine.yml }
    - { resource: packages/splash.yml }

framework:
    router:
        resource:   "%kernel.project_dir%/app/routing_test.yml"
    session:
        storage_id: session.storage.mock_file
