
################################################################################
# SPLASH Php Bundle Production Routes
splash_bundle_prod:
    resource: "@SplashBundle/Resources/config/routing.yml"
    prefix: /ws

################################################################################
# SPLASH Php Bundle Debug Routes
splash_bundle_dev:
    resource: "@SplashBundle/Resources/config/routing_dev.yml"
    prefix: /ws
    
################################################################################
# Symfony WebProfiler Routes
_wdt:
    resource:   "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:     /_wdt

################################################################################
# Symfony Profiler Routes
_profiler:
    resource:   "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:     /_profiler    